version: '3.8'

services:
  dotnetapp:
    image: dotnetapp
    container_name: dotnetapp
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - dotnetapp
    ports:
      - '80:80'
    volumes:
      - ./nginx/app.dotnet.dev.conf:/etc/nginx/conf.d/app.conf:ro
